### ISSUE TITLE
openblas测试

### ISSUE THREAD

**Issue by aureosun** [fengbingchun/Caffe_Test#1]
您好，我在csdn上面看到您成功编译了openblas的教程http://blog.csdn.net/fengbingchun/article/details/55509764，但是测试部分没有成功，所以想问您一下，测试的时候需要怎么做，试了好久也没有出结果，谢谢了

**Comment by fengbingchun** [comment]
@aureosun 后边我把openblas从静态库调整为了动态库，你再试试看看还有问题吗？我也只是简单的测试了下，但是在caffe中使用openblas时并没有发现问题。
