### ISSUE TITLE
funset not found

### ISSUE THREAD

**Issue by peyer** [fengbingchun/Caffe_Test#2]
@fengbingchun  Hi, so much thanks for your  blog about demo test of OpenBlas(https://blog.csdn.net/fengbingchun/article/details/55509764), Howevere, I found that "funset.hpp" could not found, could you provide it?

**Comment by fengbingchun** [comment]
现在的Caffe_Test中对之前的第三库的测试代码进行了一些重构，不需要funset.hpp，之前的funset.hpp中应该就是一些外部调用接口的一些声明。你直接clone最新的Caffe_Test即可编译运行。

**Comment by fengbingchun** [comment]
@peyer 现在的Caffe_Test中对之前的第三库的测试代码进行了一些重构，不需要funset.hpp，之前的funset.hpp中应该就是一些外部调用接口的一些声明。你直接clone最新的Caffe_Test即可编译运行。
